"""Add curriculum sublevel and system fields

Revision ID: 71835ffbd4db
Revises: 0001_add_idempotency_and_refund
Create Date: 2026-05-30 13:11:42.418712

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '71835ffbd4db'
down_revision = '0001_add_idempotency_and_refund'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('payments', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('uq_payments_idempotency_key'))
        batch_op.create_unique_constraint(None, ['idempotency_key'])

    with op.batch_alter_table('wallet_transactions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('uq_wallet_transactions_idempotency_key'))
        batch_op.create_unique_constraint(None, ['idempotency_key'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('wallet_transactions', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='unique')
        batch_op.create_index(batch_op.f('uq_wallet_transactions_idempotency_key'), ['idempotency_key'], unique=1)

    with op.batch_alter_table('payments', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='unique')
        batch_op.create_index(batch_op.f('uq_payments_idempotency_key'), ['idempotency_key'], unique=1)

    # ### end Alembic commands ###
