"""empty message

Revision ID: 82002b9f9238
Revises: 71835ffbd4db
Create Date: 2026-05-30 20:44:55.260356

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '82002b9f9238'
down_revision = '71835ffbd4db'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    #op.drop_table('education_system')
    with op.batch_alter_table('curriculum_system', schema=None) as batch_op:
        batch_op.create_unique_constraint('uq_curriculum_system_tag', ['tag'])

    with op.batch_alter_table('levels', schema=None) as batch_op:
        batch_op.add_column(sa.Column('curriculum_system_id', sa.Integer(), nullable=False))
        # FIX: Named the foreign key constraint explicitly
        batch_op.create_foreign_key('fk_levels_curriculum_system_id', 'curriculum_system', ['curriculum_system_id'], ['id'])
        batch_op.drop_column('curriculum_system')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    
    # 1. Handle table drops/creations first to clean up dependencies
    with op.batch_alter_table('curriculum_system', schema=None) as batch_op:
        batch_op.drop_constraint('uq_curriculum_system_tag', type_='unique')

    # 2. Modify the levels table safely
    with op.batch_alter_table('levels', schema=None) as batch_op:
        # STEP A: Drop the foreign key constraint FIRST
        # If it still throws an error, comment out this drop_constraint line entirely
        batch_op.drop_constraint('fk_levels_curriculum_system_id', type_='foreignkey')
        
        # STEP B: Drop the new column
        batch_op.drop_column('curriculum_system_id')
        
        # STEP C: Add the old column back as nullable=True first to avoid SQLite constraints crashing,
        # OR comment it out if you don't actually need the old column data right now.
        batch_op.add_column(sa.Column('curriculum_system', sa.VARCHAR(length=10), nullable=True))

    # 3. Recreate the old table last
    op.create_table('education_system',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('name', sa.VARCHAR(length=100), nullable=False),
    sa.Column('tag', sa.VARCHAR(length=100), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('tag')
    )
    # ### end Alembic commands ###

    # ### end Alembic commands ###
