"""empty message

Revision ID: c2a06b752e52
Revises: 82002b9f9238
Create Date: 2026-06-12 12:28:24.031543

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c2a06b752e52'
down_revision = '82002b9f9238'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('subjects', schema=None) as batch_op:
        batch_op.alter_column('curriculum_system',
               existing_type=sa.VARCHAR(length=10),
               type_=sa.Integer(),
               existing_nullable=True, # Explicitly mark existing state
               nullable=True)
        # Replaced None with an explicit constraint name 'fk_subjects_curriculum_system'
        batch_op.create_foreign_key('fk_subjects_curriculum_system', 'curriculum_system', ['curriculum_system'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('subjects', schema=None) as batch_op:
        # Replaced None with the explicit constraint name to allow SQLite to drop it
        batch_op.drop_constraint('fk_subjects_curriculum_system', type_='foreignkey')
        batch_op.alter_column('curriculum_system',
               existing_type=sa.Integer(),
               type_=sa.VARCHAR(length=10),
               nullable=True) # Fixed from False to True to match your model structure

    # ### end Alembic commands ###
